### ISSUE TITLE
Hot water/heating support as mqtt value

### ISSUE THREAD

**Issue by kroon040** [proddy/EMS-ESP-Boiler#10]
Hi,

It should be nice to have an mqtt value published if hot water is used , and when heating is used.

regards Richard

**Comment by proddy** [comment]
I agree. I'll see about adding that, or someone else. it's github after all and all contributions & pull requests welcome ;-)

**Comment by proddy** [comment]
latest update should fix this

**Comment by kroon040** [comment]
It works now as expected
