### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by pipovanpimperzele** [proddy/EMS-ESP-Boiler#12]
Hi,

I am trying to compile using platformio.
I am getting an error. 
[compile.txt](https://github.com/proddy/EMS-ESP-Boiler/files/2685511/compile.txt)

What could be wrong?

**Comment by proddy** [comment]
Looks like the toolchain can't find the libraries. Are you running this using VSCode or the CLI version of platformIO. Make sure you've updated all the libraries and dependencies and run again with verbose mode.

**Comment by pipovanpimperzele** [comment]
to be honest, this is the first time I am using VSC/platformIO. 
What I do is:
I go to terminal -> run build task --> choose PlatformIO: build (d1_mini)

**Comment by proddy** [comment]
no worries! If you're not really a developer then the easiest way to download, compile and upload is following my instructions in the [doc](https://github.com/proddy/EMS-ESP-Boiler#using-platformio-standalone). 

1. On Windows10 start a bash shell (https://docs.microsoft.com/en-us/windows/wsl/install-win10)
2. % pip install -U platformio
3. % sudo platformio upgrade
4. % platformio platform update
5. % git clone https://github.com/proddy/EMS-ESP-Boiler.git
6. % cd EMS-ESP-Boiler
7. % cp platformio.ini-example platformio.ini
8. % platformio run -t upload

After the 1st time just refresh from git and repeat step 8

**Comment by pipovanpimperzele** [comment]
compile is ok now. Thx!
