### ISSUE TITLE
Changelog: Removed support for older RC20 thermostat

### ISSUE THREAD

**Issue by Bonusbartus** [proddy/EMS-ESP-Boiler#17]
**Question**
*A clear and concise description of what the problem/doubt is.*
Hi Proddy, I noticed in the changelog that you removed "support for older rc20 thermostats"
What does this mean? I just started plating around with your code a week ago. I am using a Moduline 300 0x17 thermostat in combination with a Nefit Topline Compact HRC 30.
Is this an RC20 or RC30 thermostat? Can I update to the latest revision of your code?
 Transcript below.

Thanks!

**Device information**

SSH Session Transcript

Host: boiler
Date: dinsdag 25 december 2018
---------------------------------
Trying 192.168.1.109...
Connected to boiler.
Escape character is '^]'.
**********************************************
* Remote Telnet Command Center & Log Monitor *
**********************************************
* Device hostname: boiler IP: 192.168.1.109 MAC address: 5C:CF:7F:34:33:F8
* Connected to WiFi AP: Magnetron
* Boot time: start
* Free RAM: 36408 bytes
*
* Commands:
* ?=this help, q=quit telnet, $=show free memory, !=reboot, &=suspend all notifications
* v [n] set logging (0=none, 1=basic, 2=thermostat only, 3=verbose)
* s show statistics
* h list supported EMS telegram type IDs
* P publish all stat to MQTT
* p toggle EMS Poll response on/off
* S toggle Shower timer on/off
* A toggle shower Alert on/off
* b [xx] boiler request (xx=telegram type ID)
* w [nn] set boiler warm water temperature (min 30)
* a [n] boiler warm water (1=on, 2=off)
* t [xx] thermostat request (xx=telegram type ID)
* T [xx] set thermostat temperature
* m [n] set thermostat mode (1=manual, 2=auto)
* x [xx] experimental code for debugging.
v 3
(00:34:55) System Logging is set to Verbose
(00:35:00) Publishing boiler data via MQTT
(00:35:00) Requesting type UBAParameterWW(0x33) from dest 0x08
(00:35:00) Sending read to 0x08: telegram: 0B 88 33 00 63 3B (len 6)
(00:35:00) Noisy data: telegram: 00 63 3B (len 3)
(00:35:00) Boiler -> me, type 0x33 telegram: 08 0B 33 00 08 FF 3C FB 00 14 FF 02 46 D8 FF E7 (len 16)
(00:35:00) (00:35:00) Boiler -> all, type 0x07 telegram: 08 00 07 00 0B 80 00 00 00 00 00 00 00 00 00 00 00 47 (len 18)
(00:35:00) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:35:04) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 80 05 00 01 01 00 62 01 62 80 00 01 A6 00 00 0F 30 45 01 09 00 00 00 F7 (len 30)
(00:35:04) (00:35:04) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 62 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 C0 (len 22)
(00:35:04) (00:35:14) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 80 05 00 01 01 00 62 01 62 80 00 01 A6 00 00 0F 30 45 01 09 00 00 00 F7 (len 30)
(00:35:14) (00:35:14) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 62 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 C0 (len 22)
(00:35:14) (00:35:24) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 80 05 00 01 01 00 62 01 62 80 00 01 A6 00 00 0F 30 45 01 09 00 00 00 F7 (len 30)
(00:35:24) (00:35:24) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 62 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 C0 (len 22)
(00:35:24) (00:35:30) Requesting type RC20Temperature(0xA8) from dest 0x17
(00:35:30) Sending read to 0x17: telegram: 0B 97 A8 00 63 9D (len 6)
(00:35:30) Noisy data: telegram: 00 63 9D (len 3)
(00:35:30) Thermostat -> me, type 0xA8 telegram: 17 0B A8 00 01 00 FF F6 01 06 00 01 0D 03 00 FF FF 01 02 02 02 00 00 05 28 05 28 02 1E 00 FF C8 (len 32)
(00:35:30) (00:35:30) Boiler -> all, type 0x07 telegram: 08 00 07 00 0B 80 00 00 00 00 00 00 00 00 00 00 00 47 (len 18)
(00:35:31) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:35:34) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 80 05 00 01 01 00 62 01 62 80 00 01 A5 00 00 0F 30 45 01 09 00 00 00 5B (len 30)
(00:35:34) (00:35:34) Boiler -> all, type 0x19 telegram: 08 00 19 00 80 00 01 B5 80 00 00 00 00 00 02 99 43 0D 88 37 00 00 00 0B 09 1B 00 C9 C0 00 00 23 (len 32)
(00:35:34) (00:35:34) Publishing boiler data via MQTT
(00:35:34) Boiler -> all, type 0x1C telegram: 08 00 1C 00 92 0B 01 0A 0D 00 00 00 00 00 00 6C (len 16)
(00:35:34) (00:35:34) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 62 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 C0 (len 22)
(00:35:34) (00:35:35) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:35:36) Thermostat -> all, type 0x91 telegram: 17 00 91 00 80 28 00 C9 31 00 00 00 05 5A 04 00 C9 00 C6 (len 19)
(00:35:36) (00:35:37) Thermostat -> all, type 0x06 telegram: 17 00 06 00 12 0C 16 19 0E 2E 01 00 00 00 00 00 00 A9 (len 18)
(00:35:37) (00:35:37) UBASetPoint: SetPoint=90, hk_power=5 ww_power=0
(00:35:37) Thermostat -> Boiler, type 0x1A telegram: 17 08 1A 00 5A 05 00 00 CC (len 9)
(00:35:37) (00:35:38) Thermostat -> all, type 0xA3 telegram: 17 00 A3 00 00 00 00 77 (len 8)
(00:35:38) (00:35:44) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7F 05 00 01 01 00 62 01 62 80 00 01 A5 00 00 0F 30 45 01 09 00 00 00 02 (len 30)
(00:35:44) (00:35:44) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 62 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 C0 (len 22)
(00:35:44) (00:35:53) Thermostat -> Boiler, type 0x35 telegram: 17 08 35 00 11 00 C1 (len 7)
(00:35:54) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7F 05 00 01 01 00 62 01 62 80 00 01 A5 00 00 0F 30 45 01 09 00 00 00 02 (len 30)
(00:35:54) (00:35:54) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 62 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 C0 (len 22)
(00:35:54) (00:36:00) Requesting type UBAParameterWW(0x33) from dest 0x08
(00:36:00) Sending read to 0x08: telegram: 0B 88 33 00 63 3B (len 6)
(00:36:00) Noisy data: telegram: 00 63 3B (len 3)
(00:36:00) Boiler -> me, type 0x33 telegram: 08 0B 33 00 08 FF 3C FB 00 14 FF 02 46 D8 FF E7 (len 16)
(00:36:00) (00:36:00) Publishing boiler data via MQTT
(00:36:00) Boiler -> all, type 0x07 telegram: 08 00 07 00 0B 80 00 00 00 00 00 00 00 00 00 00 00 47 (len 18)
(00:36:00) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:36:04) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7F 05 00 01 01 00 62 01 61 80 00 01 A5 00 00 0F 30 45 01 09 00 00 00 38 (len 30)
(00:36:04) (00:36:04) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:36:04) (00:36:14) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7F 05 00 01 01 00 62 01 61 80 00 01 A4 00 00 0F 30 45 01 09 00 00 00 5C (len 30)
(00:36:14) (00:36:14) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:36:14) (00:36:24) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7E 05 00 01 01 00 62 01 61 80 00 01 A5 00 00 0F 30 45 01 09 00 00 00 E7 (len 30)
(00:36:24) (00:36:24) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:36:24) (00:36:30) Requesting type RC20Temperature(0xA8) from dest 0x17
(00:36:30) Sending read to 0x17: telegram: 0B 97 A8 00 63 9D (len 6)
(00:36:30) Noisy data: telegram: 00 63 9D (len 3)
(00:36:30) Thermostat -> me, type 0xA8 telegram: 17 0B A8 00 01 00 FF F6 01 06 00 01 0D 03 00 FF FF 01 02 02 02 00 00 05 28 05 28 02 1E 00 FF C8 (len 32)
(00:36:30) (00:36:30) Boiler -> all, type 0x07 telegram: 08 00 07 00 0B 80 00 00 00 00 00 00 00 00 00 00 00 47 (len 18)
(00:36:31) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:36:34) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7E 05 00 01 01 00 62 01 61 80 00 01 A4 00 00 0F 30 45 01 09 00 00 00 83 (len 30)
(00:36:34) (00:36:34) Boiler -> all, type 0x19 telegram: 08 00 19 00 80 00 01 B5 80 00 00 00 00 00 02 99 43 0D 88 37 00 00 00 0B 09 1B 00 C9 C0 00 00 23 (len 32)
(00:36:34) (00:36:34) Publishing boiler data via MQTT
(00:36:34) Boiler -> all, type 0x1C telegram: 08 00 1C 00 92 0B 01 0A 0D 00 00 00 00 00 00 6C (len 16)
(00:36:34) (00:36:34) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:36:34) (00:36:35) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:36:37) Thermostat -> all, type 0x91 telegram: 17 00 91 00 80 28 00 C9 31 00 00 00 05 5A 04 00 C9 00 C6 (len 19)
(00:36:37) (00:36:37) Thermostat -> all, type 0x06 telegram: 17 00 06 00 12 0C 16 19 0F 2E 01 00 00 00 00 00 00 B0 (len 18)
(00:36:37) (00:36:37) UBASetPoint: SetPoint=90, hk_power=5 ww_power=0
(00:36:37) Thermostat -> Boiler, type 0x1A telegram: 17 08 1A 00 5A 05 00 00 CC (len 9)
(00:36:37) (00:36:38) Thermostat -> all, type 0xA3 telegram: 17 00 A3 00 00 00 00 77 (len 8)
(00:36:38) (00:36:44) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7E 05 00 01 01 00 62 01 61 80 00 01 A4 00 00 0F 30 45 01 09 00 00 00 83 (len 30)
(00:36:44) (00:36:44) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:36:44) (00:36:44) Thermostat -> all, type 0xA2 telegram: 17 00 A2 00 00 00 00 00 00 00 00 00 00 00 00 00 00 51 (len 18)
(00:36:53) Thermostat -> Boiler, type 0x35 telegram: 17 08 35 00 11 00 C1 (len 7)
(00:36:54) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7E 05 00 01 01 00 62 01 61 80 00 01 A4 00 00 0F 30 45 01 09 00 00 00 83 (len 30)
(00:36:54) (00:36:54) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:36:54) (00:37:00) Requesting type UBAParameterWW(0x33) from dest 0x08
(00:37:00) Sending read to 0x08: telegram: 0B 88 33 00 63 3B (len 6)
(00:37:00) Noisy data: telegram: 00 63 3B (len 3)
(00:37:00) Boiler -> me, type 0x33 telegram: 08 0B 33 00 08 FF 3C FB 00 14 FF 02 46 D8 FF E7 (len 16)
(00:37:00) (00:37:00) Boiler -> all, type 0x07 telegram: 08 00 07 00 0B 80 00 00 00 00 00 00 00 00 00 00 00 47 (len 18)
(00:37:01) Boiler -> all, type 0x07 telegram: 08 00 07 00 03 80 00 00 00 00 00 00 00 00 00 00 00 6B (len 18)
(00:37:04) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7E 05 00 01 01 00 62 01 61 80 00 01 A3 00 00 0F 30 45 01 09 00 00 00 A6 (len 30)
(00:37:04) (00:37:04) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:37:04) (00:37:14) Boiler -> all, type 0x18 telegram: 08 00 18 00 4C 01 7E 05 00 01 01 00 62 01 61 80 00 01 A3 00 00 0F 30 45 01 09 00 00 00 A6 (len 30)
(00:37:14) (00:37:14) Boiler -> all, type 0x34 telegram: 08 00 34 00 3C 01 61 80 00 21 00 00 03 00 02 7F 1C 01 CF 83 00 FA (len 22)
(00:37:14) 
---------------------------------

**Comment by proddy** [comment]
Yes, I got confused with the RC20/30/35 from Buderus and the Dutch Nefit's Moduline series. **bbqkees** lent me a Moduline 400 which turns out to be an RC30 so I kinda determined the Moduline 300 must be an RC20. The latest code supports both so you should be fine. 

Happy Holidays !

From ems.h 

```
#define EMS_ID_THERMOSTAT_RC20 0x17 // RC20 (e.g. Moduline 300)
#define EMS_ID_THERMOSTAT_RC30 0x10 // RC30 (e.g. Moduline 400)
#define EMS_ID_THERMOSTAT_EASY 0x18 // TC100 (Nefit Easy)
```
