### ISSUE TITLE
some findings after first usage

### ISSUE THREAD

**Issue by SpaceTeddy** [proddy/EMS-ESP-Boiler#21]
dear proddy,

thank again for your amazing code. I received bbqkees converter board today and started the work to adjust the Sieger es73 to your code. Basically it seems that this type is a mix of RC30 and RC35. Look and feel like a RC30, but some codes are different.
However, I've made following changes:

- get / set thermostat temperatures (Set and current temp.)
**ems.h**
`
#define EMS_TYPE_RC30StatusMessage 0x3E // is an automatic thermostat broadcast giving us temps
#define EMS_TYPE_RC30Set 0x3D                     // for setting values like temp and mode
#define EMS_OFFSET_RC30Set_mode 7            // position of thermostat mode
#define EMS_OFFSET_RC30Set_temp 2             // position of thermostat setpoint temperature
#define EMS_OFFSET_RC30curr_temp 3     // position of thermostat current temperature
`
**ems.cpp**
`
void _process_RC30StatusMessage(uint8_t * data, uint8_t length) {
    EMS_Thermostat.setpoint_roomTemp = ((float)data[EMS_OFFSET_RC30Set_temp]) / (float)EMS_OFFSET_RC30Set_temp;
    EMS_Thermostat.curr_roomTemp     = _toFloat(EMS_OFFSET_RC30curr_temp, data);
    EMS_Sys_Status.emsRefreshed = true; // triggers a send the values back to Home Assistant via MQTT
}
`

- get / set thermostat mode (night/day/auto)
**boiler.ino**
`
    {"m [n]", "set thermostat mode (0=night, 1=day, 2=auto)"}, // for night/day/auto mode
`

`myDebug("  Mode is set to ");
        if (EMS_Thermostat.mode == 0) {
            myDebug("low\n");
        } else if (EMS_Thermostat.mode == 1) {
            myDebug("manual\n");
        } else if (EMS_Thermostat.mode == 2) {
            myDebug("auto\n");
        } else {
            myDebug("?\n");
            // myDebug("? (value is %d)\n", EMS_Thermostat.mode);
        }
`

**minor issues**
- burnStarts, burnWorkMin, heatWorkMin are 3 bytes long
- void _renderIntValue(const char * prefix, const char * postfix, **uint32_t** value) also 3 bytes long
- char * _int_to_char(char * s, **uint32_t** value) also 3 bytes long
- OTA update with macOS and PlatformIO does not work. It stucks at recognising the esp8266. If i start it manually, it starts, but finishes with an error message
espota.py -i 192.168.0.202 -p 8266 -f .pioenvs/nodemcuv2/firmware.bin 
Sending invitation to 192.168.0.203 
Uploading.....................................................................................................................................................................................................................................................................
16:30:14 [ERROR]: 576OK 
- I get error messages if I want to send something ... (01:24:00) Corrupt telegram: telegram: 00 63 (CRC=3B). any idea?

hope to get more time to add parsing for full type 0x3D & 0x3E thermostat messages

merci,
Chris

**Comment by proddy** [comment]
I think I've fixed most of these in my latest 1.2 version. Please check when you have a chance
