### ISSUE TITLE
CTRL-D quit not working on OSX

### ISSUE THREAD

**Issue by sysrun** [proddy/EMS-ESP-Boiler#28]
CTRL-D exit from Telnet is not working

**Comment by SpaceTeddy** [comment]
for me it works with MacOS and german keyboard setting. 
... sry, I use "ctrl-d" and not ctrl-<shift>d

**Comment by proddy** [comment]
0x04 is the standard control character for EOF on Terminals, including Telnet. On a Mac you may have to use Control-Option-D. I have a feeling ctrl-d on OSX sends two bytes 0xFF, 0xEC but can't check because i don't have a Macbook anymore.
