### ISSUE TITLE
findings V 1.2.3

### ISSUE THREAD

**Issue by SpaceTeddy** [proddy/EMS-ESP-Boiler#29]
only related to ES73 aka RC35 compatible types:

- night/day/auto mode -> offset is **7** .... 6 should be Room-offset setting -> verified with my boiler
`#define EMS_OFFSET_RC35Set_mode 7             // position of thermostat mode`

- void _process_RC35StatusMessage(uint8_t * data, uint8_t length) , we have to read the Thermostat current_temp from here (0x3E) as well! Offset is 3.
`#define EMS_TYPE_RC35StatusMessage_curr 3     // current temp`
`EMS_Thermostat.curr_roomTemp = _toFloat(EMS_TYPE_RC35StatusMessage_curr, data);`

- MQTT buffers
please increase the buffers a bit. Sometimes, the thermostat_data messsage is not complete. 524 bytes works for me

**Comment by proddy** [comment]
oops, The offset 7 vs 6 is a bug my side. I can't count. Fixed.

What I really need is someone with an official RC35 that can confirm the 0x3E has the current temp at offset 3.

**Comment by proddy** [comment]
buffer increased from 500 to 600

**Comment by proddy** [comment]
and made your changes in 1.2.4

**Comment by SpaceTeddy** [comment]
please increase also StaticJsonBuffer<512> jsonBuffer;
without increasing this JsonBuffer, the thermostat_data message is not complete

thx and have a good sleep.

**Comment by proddy** [comment]
done
