### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by yctn** [proddy/EMS-ESP-Boiler#3]
Hi,

im trying to compile the sketch using the arduino IDE.

i get the following error:
Archiving built core (caching) in: /var/folders/6r/tdsrvmt14wvfj9ryqjmrtlmm0000gn/T/arduino_cache_136986/core/core_esp8266_esp8266_d1_mini_CpuFrequency_80,UploadSpeed_921600,FlashSize_4M3M_e7d7afb0d813ff49b3b3c7a623d8ce4d.a
sketch/boiler.ino.cpp.o: In function `_float_to_char(char*, float, unsigned char)':
/Users/user/Documents/Arduino/boiler/boiler.ino:609: undefined reference to `strtof'
sketch/boiler.ino.cpp.o: In function `MQTTcallback(char*, unsigned char*, unsigned char)':
/Users/user/Documents/Arduino/boiler/boiler.ino:609: undefined reference to `strtof'
sketch/boiler.ino.cpp.o: In function `myDebugCallback()':
/Users/user/Documents/Arduino/boiler/boiler.ino:400: undefined reference to `strtof'
sketch/emsuart.cpp.o: In function `emsuart_recvTask(ETSEventTag*)':
emsuart.cpp:(.irom0.text+0x7c): undefined reference to `system_os_task(void (*)(ETSEventTag*), unsigned char, ETSEventTag*, unsigned char)'
emsuart.cpp:(.irom0.text+0x80): undefined reference to `system_uart_swap()'
sketch/emsuart.cpp.o: In function `emsuart_init()':
sketch/emsuart.cpp:116: undefined reference to `system_os_task(void (*)(ETSEventTag*), unsigned char, ETSEventTag*, unsigned char)'
sketch/emsuart.cpp:121: undefined reference to `system_uart_swap()'
sketch/emsuart.cpp.o:(.text._ZL23emsuart_rx_intr_handlerPv+0x1c): undefined reference to `system_os_post(unsigned char, unsigned int, unsigned int)'
sketch/emsuart.cpp.o: In function `emsuart_rx_intr_handler':
sketch/emsuart.cpp:55: undefined reference to `system_os_post(unsigned char, unsigned int, unsigned int)'
Multiple libraries were found for "PubSubClient.h"
collect2: error: ld returned 1 exit status
 Used: /Users/user/Documents/Arduino/libraries/PubSubClient
 Not used: /Users/user/Documents/Arduino/libraries/ESP8266_Microgear
exit status 1
Error compiling for board WeMos D1 R2 & mini.

what could this be?

**Comment by proddy** [comment]
I don't use the Arduino IDE (as explained in the doc). Looks like some library references are missing. My advice would be to follow my guidelines in https://github.com/proddy/EMS-ESP-Boiler#using-platformio-standalone. If you find a way that works with Arduino IDE let me know and I'll update the doc.
