### ISSUE TITLE
EMS-ESP Thermostat is not recognized/added to homeassistant lovelace autodiscover

### ISSUE THREAD

**Issue by bartplessers** [proddy/EMS-ESP-Boiler#774]
Hi,

Running

- BUDERUS Logamax plus GB192iT40
- BOSCH RC310 thermostaat
- BUDERUS Gateway Logamatic web KM100
- BBQkees Gateway Premium II
- ems-esp v2.2.2
- home assistant 2021.8.8

The thermostat is discovered with it's according entities by homeassistant:
![2021-08-30_14-08-58](https://user-images.githubusercontent.com/10470708/131337068-40865463-269e-4436-b057-02273de0c0f3.png)

However, in the past, this thermostat was automatically added to the lovelace interface of homeassistant.
Recently, I reinstalled my instance of homeassistant, and I notice that the thermostat does **not** show up anymore.

Also, If I add the entities manually to the dashboard, the thermostat seems "unavailable":
![2021-08-30_14-16-21](https://user-images.githubusercontent.com/10470708/131337565-2b05a8dd-2563-4458-9079-c09d7e2142fc.png)

On MQTT Explorer, I see data coming in:
![2021-08-30_14-17-53](https://user-images.githubusercontent.com/10470708/131337757-7d4d1aba-7e38-45c5-9680-2d893f64163c.png)

Question:
How can I add the thermostat to my homeassistant dashboard.

kind regards,
Bart Plessers

**Comment by proddy** [comment]
go into MQTTExplorer and see if the Discovery topics are there. Search for `hc1`. This is what I see:

![Screenshot 2021-08-30 202640](https://user-images.githubusercontent.com/1230712/131386846-8fe4325a-4f7c-4ca2-9c24-33cb321e1995.png)

Also I'm no longer supporting the ESP8266 so I would strongly recommend swapping it out for an ESP32 and jumping over to v3. You're missing out on a lot of cool new features.

**Comment by bartplessers** [comment]
Hi @proddy ,

I do have (more or less) the 'sensor' topics:
![2021-08-31_1-42-55](https://user-images.githubusercontent.com/10470708/131419580-7287b088-21d3-4704-822f-0eaf444fe3bd.png)


but I'm missing the 'climate' topic:
![2021-08-31_1-45-25](https://user-images.githubusercontent.com/10470708/131419758-dd797a5c-282f-471c-82d3-9a7effe1e027.png)


That's probably the reason why HA does not recognize the thermostat...

Any idea why?


>Also I'm no longer supporting the ESP8266 so I would strongly recommend swapping it out for an ESP32 and jumping over to v3. You're missing out on a lot of cool new features.

I will give it a try in the future, but I recently (+/- 1Year ago) bought a BBQkees Gateway Premium II (P2), so If I get this working, it's fine for nox.


grtz 
B

**Comment by proddy** [comment]
I'm not sure what is causing this, assuming you hadn't upgrade the firmware or changed the settings (like tx_delay). I would again strongly recommend you buy an ESP32 for 4 euros and swap it out on your Premium II board.

**Comment by bbqkees** [comment]
What sometimes does help is removing the Gateway from power/ bus completely and then connect it again after 20 seconds.
Sometimes rebooting via the web is not enough.

**Comment by bartplessers** [comment]
@bbqkees : thanx! that did the trick!!!
@proddy : _swap to ESP32_: will do. But first I have to practice my solder skills. It has been a while ago and at least I have to find my soldering iron first... :-)

**Comment by proddy** [comment]
@bartplessers I'm sure if you send it back to Kees he'll solder it for free :-)

**Comment by bartplessers** [comment]
Hi @proddy , 

I have saved @bbqkees to solder my ESP32, and finally found some time to do it myself.
Things went well and running v3.2.1 now on ESP32 / v3.3.5-1-g85c43024c

thanx for your mental support 

grtz
B

**Comment by proddy** [comment]
That's awesome news @bartplessers ! I hope you like all the new features
