### ISSUE TITLE
Home Assistant MQTT Auto Discovery only discovering dallas sensor

### ISSUE THREAD

**Issue by RobbeM1991** [proddy/EMS-ESP-Boiler#775]
I've got a Gateway Premium II (P2), running esp8266 / 2.2.2-dev(38a443e).
Running Home Assistant 2021.8.8.
With addon: Mosquitto broker Current version: 6.0.1

I've followed the explanation at https://bbqkees-electronics.nl/wiki/gateway/home-assistant-configuration.html to configure MQTT auto discovery.

The MQTT integration only finds a dallas sensor but can't find my boiler or thermostat.

Any tips on how to find the boiler too?
Am I doing something wrong or has something changed since the date of the tutorial?
Did I forget something?

**Comment by proddy** [comment]
I'm not sure. Version 2 for the ESP8266 was discontinued quite a while ago (I would strongly suggest swapping out the ESP8266 for an ESP32 and using v3). Anyway, use MQTTExplorer and take a peek at the topics that start with 'homeassistant'. Also look into HA at the Integrations to see what is listed. There are some notes on this at https://emsesp.github.io/docs/#/Home-Assistant

**Comment by bbqkees** [comment]
Did it work before? 

If you changed settings on EMS-ESP V2 save them and then disconnect the Gateway from the power completely and connect it back.

The HA guide on the wiki was created with V2 at the time so the direction should still be correct.

**Comment by RobbeM1991** [comment]
> 
> 
> I'm not sure. Version 2 for the ESP8266 was disconnected quite a while ago (I would strongly suggest swapping out the ESP8266 for an ESP32 and using v3). Anyway, use MQTTExplorer and take a peek at the topics that start with 'homeassistant'. Also look into HA at the Integrations to see what is listed. There's some notes on this at https://emsesp.github.io/docs/#/Home-Assistant
![MQTT_ha_ams_esp](https://user-images.githubusercontent.com/47741753/132306688-46b3fd1b-1805-4f5d-82df-ee9c33f5558e.png)

I just took a look through MQTT explorer.
The boiler info is published, but not under homeassistant... Any possible reason for that?

Also, it seems that I can't configure the temperature setpoint as settable in the ems-esp web interface, would I be able to do that with the ESP32 version or would that remain the same?

**Comment by bbqkees** [comment]
Remove the Gateway from power completely and reconnect it after 20 seconds.
Likely the MQTT discovery topics will be sent for the boiler/thermostat as well.

**Comment by RobbeM1991** [comment]
> 
> 
> Remove the Gateway from power completely and reconnect it after 20 seconds.
> Likely the MQTT discovery topics will be sent for the boiler/thermostat as well.

Thanks! It's working now.
Pretty stupid of me not having tried that first though...

It seems I can also set the temperature of the thermostat, which is what I wanted.
The wiki (https://bbqkees-electronics.nl/wiki/gateway/home-assistant-configuration.html?highlight=settable) said that the parameter needed to have a pencil in front of it on the web interface, to be settable. In this case it doesn't.

But it's working and that's most important!

Thanks for creating this really nice device!

**Comment by proddy** [comment]
great! happy that it works

**Comment by bbqkees** [comment]
The pencil was introduced in V3 so it's not in the V2 firmware.

**Comment by proddy** [comment]
btw there's a demo of V3 at https://ems-esp.derbyshire.nl although it's a slightly older version but still gives you an idea of the new features and settings
